# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180424_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='label',
        ),
        migrations.RemoveField(
            model_name='bloglabel',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogArticle',
        ),
        migrations.DeleteModel(
            name='BlogLabel',
        ),
    ]
